### PR TITLE
nickwaller/ch108/basic-site-structure

### PR DESCRIPTION
**Pull request by ooOsH**

### CODE REVIEW

**Comment by elliotmitchell** [comment]
I'm guessing you'll want the vagrant file port 1337 to point to 4444 instead of 80?

**Comment by elliotmitchell** [comment]
...and maybe you don't need apache with this web

**Comment by ooOsH** [comment]
> I'm guessing you'll want the vagrant file port 1337 to point to 4444 instead of 80?

Shall I add this on a new PR when I have the main fork?

**Comment by ooOsH** [comment]
> ...and maybe you don't need apache with this web

Yeah seems pretty much self serving but we'll see just incase as it's new to me

**Pull request merged**
